export type ContainerScopeType =
  | 'default'
  | 'middleware'
  | 'service'
  | 'storage'
  | 'repository'
  | 'database'
  | 'validator'
  | 'assert'
  | 'config'
  | 'controller'
  | 'seed'
  | 'mailer'
  | 'vector'
  | 'permission';
