export const assertMapper: Record<string, string> = {
  Array: 'AssertArray',
  string: 'AssertString',
  stringArray: 'AssertStringArray',
  null: 'AssertNull',
  nullArray: 'AssertNullArray',
  number: 'AssertNumber',
  numberArray: 'AssertNumberArray',
  boolean: 'AssertBoolean',
  booleanArray: 'AssertBooleanArray',
  undefined: 'AssertUndefined',
  undefinedArray: 'AssertUndefinedArray',
  Date: 'AssertDate',
  DateArray: 'AssertDateArray',
  bigint: 'AssertBigint',
  bigintArray: 'AssertBigintArray',
};
